### PR TITLE
maintenance: deploy to Github Pages from a CI job

### PR DESCRIPTION
**Pull request by igrr**
With this change, we don't need to:
- maintain or update gh-pages branch
- vendor node_modules directory into the source tree.

A CI job will trigger every time the `main` branch is updated. This job will download node_modules and upload the project to Github Pages.

Example of a successful deployment can be seen in the fork: https://igrr.github.io/esp-launchpad/

### CODE REVIEW

**Comment by igrr** [comment]
I have also synced the esptool-js code to the latest version in https://github.com/igrr/esp-launchpad/tree/dev to allow ESP32-S3 to work, will make another PR once this one is merged.

**Comment by brianignacio5** [comment]
LGTM !

I would suggest in the future to bundle the project in a single js for example (to increase the speed of esp-launchpad loading in web).

Also Esptool-js could be used as npm dependency here instead of hard copy of the files, but I noticed there are some changes between web serial.js here for example. Maybe we can make Esptool-js more extensible to reduce code duplication here ?

**Comment by igrr** [comment]
@brianignacio5 both suggestions make a lot of sense! 

Is esptool-js published in npm already? I have seen that you mention this in the description of https://github.com/espressif/esptool-js/pull/53 but haven't found the package name.

**Comment by adwait-esp** [comment]
LGTM

**Pull request merged**
